// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Hamekoz.Argentina.Afip.WSAA {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoginCmsSoapBinding", Namespace="https://wsaa.afip.gov.ar/ws/services/LoginCms")]
    public partial class LoginCMSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// CodeRemarks
        public LoginCMSService() {
            this.Url = "https://wsaa.afip.gov.ar/ws/services/LoginCms";
        }
        
        public LoginCMSService(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsaa.view.sua.dvadac.desein.afip.gov", ResponseNamespace="http://wsaa.view.sua.dvadac.desein.afip.gov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("loginCmsReturn")]
        public string loginCms(string in0) {
            object[] results = this.Invoke("loginCms", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginloginCms(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("loginCms", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// CodeRemarks
        public string EndloginCms(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
