// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Hamekoz.Argentina.Afip.WSAA {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="LoginCms", Namespace="https://wsaa.afip.gov.ar/ws/services/LoginCms")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCMSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginCmsOperationCompleted;
        
        public LoginCMSService() {
            this.Url = "https://wsaa.afip.gov.ar/ws/services/LoginCms";
        }
        
        public LoginCMSService(string url) {
            this.Url = url;
        }
        
        public event loginCmsCompletedEventHandler loginCmsCompleted;
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsaa.view.sua.dvadac.desein.afip.gov", ResponseNamespace="http://wsaa.view.sua.dvadac.desein.afip.gov", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("loginCmsReturn")]
        public string loginCms(string in0) {
            object[] results = this.Invoke("loginCms", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        public System.IAsyncResult BeginloginCms(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("loginCms", new object[] {
                        in0}, callback, asyncState);
        }
        
        public string EndloginCms(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        public void loginCmsAsync(string in0) {
            this.loginCmsAsync(in0, null);
        }
        
        public void loginCmsAsync(string in0, object userState) {
            if ((this.loginCmsOperationCompleted == null)) {
                this.loginCmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginCmsCompleted);
            }
            this.InvokeAsync("loginCms", new object[] {
                        in0}, this.loginCmsOperationCompleted, userState);
        }
        
        private void OnloginCmsCompleted(object arg) {
            if ((this.loginCmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCmsCompleted(this, new loginCmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    public partial class loginCmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public delegate void loginCmsCompletedEventHandler(object sender, loginCmsCompletedEventArgs args);
}
