// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Hamekoz.Argentina.Afip.wsfev1 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FEDetResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECabResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FEDetRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECabRequest))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// CodeRemarks
        public Service() {
            this.Url = "https://servicios1.afip.gov.ar/wsfev1/service.asmx";
        }
        
        public Service(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECAESolicitar", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FECAEResponse FECAESolicitar(FEAuthRequest Auth, FECAERequest FeCAEReq) {
            object[] results = this.Invoke("FECAESolicitar", new object[] {
                        Auth,
                        FeCAEReq});
            return ((FECAEResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFECAESolicitar(FEAuthRequest Auth, FECAERequest FeCAEReq, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FECAESolicitar", new object[] {
                        Auth,
                        FeCAEReq}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FECAEResponse EndFECAESolicitar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FECAEResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECompTotXRequest", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FERegXReqResponse FECompTotXRequest(FEAuthRequest Auth) {
            object[] results = this.Invoke("FECompTotXRequest", new object[] {
                        Auth});
            return ((FERegXReqResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFECompTotXRequest(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FECompTotXRequest", new object[] {
                        Auth}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FERegXReqResponse EndFECompTotXRequest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FERegXReqResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEDummy", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DummyResponse FEDummy() {
            object[] results = this.Invoke("FEDummy", new object[0]);
            return ((DummyResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFEDummy(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FEDummy", new object[0], callback, asyncState);
        }
        
        /// CodeRemarks
        public DummyResponse EndFEDummy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DummyResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECompUltimoAutorizado", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FERecuperaLastCbteResponse FECompUltimoAutorizado(FEAuthRequest Auth, int PtoVta, int CbteTipo) {
            object[] results = this.Invoke("FECompUltimoAutorizado", new object[] {
                        Auth,
                        PtoVta,
                        CbteTipo});
            return ((FERecuperaLastCbteResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFECompUltimoAutorizado(FEAuthRequest Auth, int PtoVta, int CbteTipo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FECompUltimoAutorizado", new object[] {
                        Auth,
                        PtoVta,
                        CbteTipo}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FERecuperaLastCbteResponse EndFECompUltimoAutorizado(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FERecuperaLastCbteResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECompConsultar", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FECompConsultaResponse FECompConsultar(FEAuthRequest Auth, FECompConsultaReq FeCompConsReq) {
            object[] results = this.Invoke("FECompConsultar", new object[] {
                        Auth,
                        FeCompConsReq});
            return ((FECompConsultaResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFECompConsultar(FEAuthRequest Auth, FECompConsultaReq FeCompConsReq, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FECompConsultar", new object[] {
                        Auth,
                        FeCompConsReq}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FECompConsultaResponse EndFECompConsultar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FECompConsultaResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECAEARegInformativo", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FECAEAResponse FECAEARegInformativo(FEAuthRequest Auth, FECAEARequest FeCAEARegInfReq) {
            object[] results = this.Invoke("FECAEARegInformativo", new object[] {
                        Auth,
                        FeCAEARegInfReq});
            return ((FECAEAResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFECAEARegInformativo(FEAuthRequest Auth, FECAEARequest FeCAEARegInfReq, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FECAEARegInformativo", new object[] {
                        Auth,
                        FeCAEARegInfReq}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FECAEAResponse EndFECAEARegInformativo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FECAEAResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECAEASolicitar", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FECAEAGetResponse FECAEASolicitar(FEAuthRequest Auth, int Periodo, short Orden) {
            object[] results = this.Invoke("FECAEASolicitar", new object[] {
                        Auth,
                        Periodo,
                        Orden});
            return ((FECAEAGetResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFECAEASolicitar(FEAuthRequest Auth, int Periodo, short Orden, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FECAEASolicitar", new object[] {
                        Auth,
                        Periodo,
                        Orden}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FECAEAGetResponse EndFECAEASolicitar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FECAEAGetResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoConsultar", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FECAEASinMovConsResponse FECAEASinMovimientoConsultar(FEAuthRequest Auth, string CAEA, int PtoVta) {
            object[] results = this.Invoke("FECAEASinMovimientoConsultar", new object[] {
                        Auth,
                        CAEA,
                        PtoVta});
            return ((FECAEASinMovConsResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFECAEASinMovimientoConsultar(FEAuthRequest Auth, string CAEA, int PtoVta, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FECAEASinMovimientoConsultar", new object[] {
                        Auth,
                        CAEA,
                        PtoVta}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FECAEASinMovConsResponse EndFECAEASinMovimientoConsultar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FECAEASinMovConsResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoInformar", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FECAEASinMovResponse FECAEASinMovimientoInformar(FEAuthRequest Auth, int PtoVta, string CAEA) {
            object[] results = this.Invoke("FECAEASinMovimientoInformar", new object[] {
                        Auth,
                        PtoVta,
                        CAEA});
            return ((FECAEASinMovResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFECAEASinMovimientoInformar(FEAuthRequest Auth, int PtoVta, string CAEA, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FECAEASinMovimientoInformar", new object[] {
                        Auth,
                        PtoVta,
                        CAEA}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FECAEASinMovResponse EndFECAEASinMovimientoInformar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FECAEASinMovResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECAEAConsultar", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FECAEAGetResponse FECAEAConsultar(FEAuthRequest Auth, int Periodo, short Orden) {
            object[] results = this.Invoke("FECAEAConsultar", new object[] {
                        Auth,
                        Periodo,
                        Orden});
            return ((FECAEAGetResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFECAEAConsultar(FEAuthRequest Auth, int Periodo, short Orden, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FECAEAConsultar", new object[] {
                        Auth,
                        Periodo,
                        Orden}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FECAEAGetResponse EndFECAEAConsultar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FECAEAGetResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetCotizacion", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FECotizacionResponse FEParamGetCotizacion(FEAuthRequest Auth, string MonId) {
            object[] results = this.Invoke("FEParamGetCotizacion", new object[] {
                        Auth,
                        MonId});
            return ((FECotizacionResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFEParamGetCotizacion(FEAuthRequest Auth, string MonId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FEParamGetCotizacion", new object[] {
                        Auth,
                        MonId}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FECotizacionResponse EndFEParamGetCotizacion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FECotizacionResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposTributos", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FETributoResponse FEParamGetTiposTributos(FEAuthRequest Auth) {
            object[] results = this.Invoke("FEParamGetTiposTributos", new object[] {
                        Auth});
            return ((FETributoResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFEParamGetTiposTributos(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FEParamGetTiposTributos", new object[] {
                        Auth}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FETributoResponse EndFEParamGetTiposTributos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FETributoResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposMonedas", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MonedaResponse FEParamGetTiposMonedas(FEAuthRequest Auth) {
            object[] results = this.Invoke("FEParamGetTiposMonedas", new object[] {
                        Auth});
            return ((MonedaResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFEParamGetTiposMonedas(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FEParamGetTiposMonedas", new object[] {
                        Auth}, callback, asyncState);
        }
        
        /// CodeRemarks
        public MonedaResponse EndFEParamGetTiposMonedas(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MonedaResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposIva", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IvaTipoResponse FEParamGetTiposIva(FEAuthRequest Auth) {
            object[] results = this.Invoke("FEParamGetTiposIva", new object[] {
                        Auth});
            return ((IvaTipoResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFEParamGetTiposIva(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FEParamGetTiposIva", new object[] {
                        Auth}, callback, asyncState);
        }
        
        /// CodeRemarks
        public IvaTipoResponse EndFEParamGetTiposIva(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((IvaTipoResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposOpcional", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OpcionalTipoResponse FEParamGetTiposOpcional(FEAuthRequest Auth) {
            object[] results = this.Invoke("FEParamGetTiposOpcional", new object[] {
                        Auth});
            return ((OpcionalTipoResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFEParamGetTiposOpcional(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FEParamGetTiposOpcional", new object[] {
                        Auth}, callback, asyncState);
        }
        
        /// CodeRemarks
        public OpcionalTipoResponse EndFEParamGetTiposOpcional(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OpcionalTipoResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposConcepto", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConceptoTipoResponse FEParamGetTiposConcepto(FEAuthRequest Auth) {
            object[] results = this.Invoke("FEParamGetTiposConcepto", new object[] {
                        Auth});
            return ((ConceptoTipoResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFEParamGetTiposConcepto(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FEParamGetTiposConcepto", new object[] {
                        Auth}, callback, asyncState);
        }
        
        /// CodeRemarks
        public ConceptoTipoResponse EndFEParamGetTiposConcepto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ConceptoTipoResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetPtosVenta", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FEPtoVentaResponse FEParamGetPtosVenta(FEAuthRequest Auth) {
            object[] results = this.Invoke("FEParamGetPtosVenta", new object[] {
                        Auth});
            return ((FEPtoVentaResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFEParamGetPtosVenta(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FEParamGetPtosVenta", new object[] {
                        Auth}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FEPtoVentaResponse EndFEParamGetPtosVenta(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FEPtoVentaResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposCbte", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CbteTipoResponse FEParamGetTiposCbte(FEAuthRequest Auth) {
            object[] results = this.Invoke("FEParamGetTiposCbte", new object[] {
                        Auth});
            return ((CbteTipoResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFEParamGetTiposCbte(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FEParamGetTiposCbte", new object[] {
                        Auth}, callback, asyncState);
        }
        
        /// CodeRemarks
        public CbteTipoResponse EndFEParamGetTiposCbte(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CbteTipoResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposDoc", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DocTipoResponse FEParamGetTiposDoc(FEAuthRequest Auth) {
            object[] results = this.Invoke("FEParamGetTiposDoc", new object[] {
                        Auth});
            return ((DocTipoResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFEParamGetTiposDoc(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FEParamGetTiposDoc", new object[] {
                        Auth}, callback, asyncState);
        }
        
        /// CodeRemarks
        public DocTipoResponse EndFEParamGetTiposDoc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DocTipoResponse)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposPaises", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FEPaisResponse FEParamGetTiposPaises(FEAuthRequest Auth) {
            object[] results = this.Invoke("FEParamGetTiposPaises", new object[] {
                        Auth});
            return ((FEPaisResponse)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginFEParamGetTiposPaises(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FEParamGetTiposPaises", new object[] {
                        Auth}, callback, asyncState);
        }
        
        /// CodeRemarks
        public FEPaisResponse EndFEParamGetTiposPaises(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FEPaisResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FEAuthRequest {
        
        /// <remarks/>
        public string Token;
        
        /// <remarks/>
        public string Sign;
        
        /// <remarks/>
        public long Cuit;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class PaisTipo {
        
        /// <remarks/>
        public short Id;
        
        /// <remarks/>
        public string Desc;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FEPaisResponse {
        
        /// <remarks/>
        public PaisTipo[] ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class Err {
        
        /// <remarks/>
        public int Code;
        
        /// <remarks/>
        public string Msg;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class Evt {
        
        /// <remarks/>
        public int Code;
        
        /// <remarks/>
        public string Msg;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class DocTipo {
        
        /// <remarks/>
        public int Id;
        
        /// <remarks/>
        public string Desc;
        
        /// <remarks/>
        public string FchDesde;
        
        /// <remarks/>
        public string FchHasta;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class DocTipoResponse {
        
        /// <remarks/>
        public DocTipo[] ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class CbteTipo {
        
        /// <remarks/>
        public int Id;
        
        /// <remarks/>
        public string Desc;
        
        /// <remarks/>
        public string FchDesde;
        
        /// <remarks/>
        public string FchHasta;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class CbteTipoResponse {
        
        /// <remarks/>
        public CbteTipo[] ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class PtoVenta {
        
        /// <remarks/>
        public short Nro;
        
        /// <remarks/>
        public string EmisionTipo;
        
        /// <remarks/>
        public string Bloqueado;
        
        /// <remarks/>
        public string FchBaja;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FEPtoVentaResponse {
        
        /// <remarks/>
        public PtoVenta[] ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class ConceptoTipo {
        
        /// <remarks/>
        public int Id;
        
        /// <remarks/>
        public string Desc;
        
        /// <remarks/>
        public string FchDesde;
        
        /// <remarks/>
        public string FchHasta;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class ConceptoTipoResponse {
        
        /// <remarks/>
        public ConceptoTipo[] ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class OpcionalTipo {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Desc;
        
        /// <remarks/>
        public string FchDesde;
        
        /// <remarks/>
        public string FchHasta;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class OpcionalTipoResponse {
        
        /// <remarks/>
        public OpcionalTipo[] ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class IvaTipo {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Desc;
        
        /// <remarks/>
        public string FchDesde;
        
        /// <remarks/>
        public string FchHasta;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class IvaTipoResponse {
        
        /// <remarks/>
        public IvaTipo[] ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class Moneda {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Desc;
        
        /// <remarks/>
        public string FchDesde;
        
        /// <remarks/>
        public string FchHasta;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class MonedaResponse {
        
        /// <remarks/>
        public Moneda[] ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class TributoTipo {
        
        /// <remarks/>
        public short Id;
        
        /// <remarks/>
        public string Desc;
        
        /// <remarks/>
        public string FchDesde;
        
        /// <remarks/>
        public string FchHasta;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FETributoResponse {
        
        /// <remarks/>
        public TributoTipo[] ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class Cotizacion {
        
        /// <remarks/>
        public string MonId;
        
        /// <remarks/>
        public double MonCotiz;
        
        /// <remarks/>
        public string FchCotiz;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECotizacionResponse {
        
        /// <remarks/>
        public Cotizacion ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEASinMovResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEASinMov {
        
        /// <remarks/>
        public string CAEA;
        
        /// <remarks/>
        public string FchProceso;
        
        /// <remarks/>
        public int PtoVta;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEASinMovResponse : FECAEASinMov {
        
        /// <remarks/>
        public string Resultado;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEASinMovConsResponse {
        
        /// <remarks/>
        public FECAEASinMov[] ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEAGet {
        
        /// <remarks/>
        public string CAEA;
        
        /// <remarks/>
        public int Periodo;
        
        /// <remarks/>
        public short Orden;
        
        /// <remarks/>
        public string FchVigDesde;
        
        /// <remarks/>
        public string FchVigHasta;
        
        /// <remarks/>
        public string FchTopeInf;
        
        /// <remarks/>
        public string FchProceso;
        
        /// <remarks/>
        public Obs[] Observaciones;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class Obs {
        
        /// <remarks/>
        public int Code;
        
        /// <remarks/>
        public string Msg;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEAGetResponse {
        
        /// <remarks/>
        public FECAEAGet ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEAResponse {
        
        /// <remarks/>
        public FECAEACabResponse FeCabResp;
        
        /// <remarks/>
        public FECAEADetResponse[] FeDetResp;
        
        /// <remarks/>
        public Evt[] Events;
        
        /// <remarks/>
        public Err[] Errors;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEACabResponse : FECabResponse {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEACabResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAECabResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECabResponse {
        
        /// <remarks/>
        public long Cuit;
        
        /// <remarks/>
        public int PtoVta;
        
        /// <remarks/>
        public int CbteTipo;
        
        /// <remarks/>
        public string FchProceso;
        
        /// <remarks/>
        public int CantReg;
        
        /// <remarks/>
        public string Resultado;
        
        /// <remarks/>
        public string Reproceso;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAECabResponse : FECabResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEADetResponse : FEDetResponse {
        
        /// <remarks/>
        public string CAEA;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEADetResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEDetResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FEDetResponse {
        
        /// <remarks/>
        public int Concepto;
        
        /// <remarks/>
        public int DocTipo;
        
        /// <remarks/>
        public long DocNro;
        
        /// <remarks/>
        public long CbteDesde;
        
        /// <remarks/>
        public long CbteHasta;
        
        /// <remarks/>
        public string CbteFch;
        
        /// <remarks/>
        public string Resultado;
        
        /// <remarks/>
        public Obs[] Observaciones;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEDetResponse : FEDetResponse {
        
        /// <remarks/>
        public string CAE;
        
        /// <remarks/>
        public string CAEFchVto;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEARequest {
        
        /// <remarks/>
        public FECAEACabRequest FeCabReq;
        
        /// <remarks/>
        public FECAEADetRequest[] FeDetReq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEACabRequest : FECabRequest {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEACabRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAECabRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECabRequest {
        
        /// <remarks/>
        public int CantReg;
        
        /// <remarks/>
        public int PtoVta;
        
        /// <remarks/>
        public int CbteTipo;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAECabRequest : FECabRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEADetRequest : FEDetRequest {
        
        /// <remarks/>
        public string CAEA;
        
        /// <remarks/>
        public string CbteFchHsGen;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEADetRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEDetRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECompConsResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FEDetRequest {
        
        /// <remarks/>
        public int Concepto;
        
        /// <remarks/>
        public int DocTipo;
        
        /// <remarks/>
        public long DocNro;
        
        /// <remarks/>
        public long CbteDesde;
        
        /// <remarks/>
        public long CbteHasta;
        
        /// <remarks/>
        public string CbteFch;
        
        /// <remarks/>
        public double ImpTotal;
        
        /// <remarks/>
        public double ImpTotConc;
        
        /// <remarks/>
        public double ImpNeto;
        
        /// <remarks/>
        public double ImpOpEx;
        
        /// <remarks/>
        public double ImpTrib;
        
        /// <remarks/>
        public double ImpIVA;
        
        /// <remarks/>
        public string FchServDesde;
        
        /// <remarks/>
        public string FchServHasta;
        
        /// <remarks/>
        public string FchVtoPago;
        
        /// <remarks/>
        public string MonId;
        
        /// <remarks/>
        public double MonCotiz;
        
        /// <remarks/>
        public CbteAsoc[] CbtesAsoc;
        
        /// <remarks/>
        public Tributo[] Tributos;
        
        /// <remarks/>
        public AlicIva[] Iva;
        
        /// <remarks/>
        public Opcional[] Opcionales;
        
        /// <remarks/>
        public Comprador[] Compradores;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class CbteAsoc {
        
        /// <remarks/>
        public int Tipo;
        
        /// <remarks/>
        public int PtoVta;
        
        /// <remarks/>
        public long Nro;
        
        /// <remarks/>
        public string Cuit;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class Tributo {
        
        /// <remarks/>
        public short Id;
        
        /// <remarks/>
        public string Desc;
        
        /// <remarks/>
        public double BaseImp;
        
        /// <remarks/>
        public double Alic;
        
        /// <remarks/>
        public double Importe;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class AlicIva {
        
        /// <remarks/>
        public int Id;
        
        /// <remarks/>
        public double BaseImp;
        
        /// <remarks/>
        public double Importe;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class Opcional {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Valor;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class Comprador {
        
        /// <remarks/>
        public int DocTipo;
        
        /// <remarks/>
        public long DocNro;
        
        /// <remarks/>
        public double Porcentaje;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FECompConsResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEDetRequest : FEDetRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECompConsResponse : FECAEDetRequest {
        
        /// <remarks/>
        public string Resultado;
        
        /// <remarks/>
        public string CodAutorizacion;
        
        /// <remarks/>
        public string EmisionTipo;
        
        /// <remarks/>
        public string FchVto;
        
        /// <remarks/>
        public string FchProceso;
        
        /// <remarks/>
        public Obs[] Observaciones;
        
        /// <remarks/>
        public int PtoVta;
        
        /// <remarks/>
        public int CbteTipo;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECompConsultaResponse {
        
        /// <remarks/>
        public FECompConsResponse ResultGet;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECompConsultaReq {
        
        /// <remarks/>
        public int CbteTipo;
        
        /// <remarks/>
        public long CbteNro;
        
        /// <remarks/>
        public int PtoVta;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FERecuperaLastCbteResponse {
        
        /// <remarks/>
        public int PtoVta;
        
        /// <remarks/>
        public int CbteTipo;
        
        /// <remarks/>
        public int CbteNro;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class DummyResponse {
        
        /// <remarks/>
        public string AppServer;
        
        /// <remarks/>
        public string DbServer;
        
        /// <remarks/>
        public string AuthServer;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FERegXReqResponse {
        
        /// <remarks/>
        public int RegXReq;
        
        /// <remarks/>
        public Err[] Errors;
        
        /// <remarks/>
        public Evt[] Events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAEResponse {
        
        /// <remarks/>
        public FECAECabResponse FeCabResp;
        
        /// <remarks/>
        public FECAEDetResponse[] FeDetResp;
        
        /// <remarks/>
        public Evt[] Events;
        
        /// <remarks/>
        public Err[] Errors;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
    public partial class FECAERequest {
        
        /// <remarks/>
        public FECAECabRequest FeCabReq;
        
        /// <remarks/>
        public FECAEDetRequest[] FeDetReq;
    }
}
