
// This file has been generated by the GUI designer. Do not modify.
namespace DatePicker
{
	public partial class DialogCalendar
	{
		private global::Gtk.Calendar calendar;
		
		private global::Gtk.Button buttonToday;
		
		private global::Gtk.Button buttonDefault;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DatePicker.DialogCalendar
			this.Name = "DatePicker.DialogCalendar";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.Decorated = false;
			// Internal child DatePicker.DialogCalendar.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.calendar = new global::Gtk.Calendar ();
			this.calendar.CanFocus = true;
			this.calendar.Name = "calendar";
			this.calendar.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			w1.Add (this.calendar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.calendar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Internal child DatePicker.DialogCalendar.ActionArea
			global::Gtk.HButtonBox w3 = this.ActionArea;
			w3.Name = "dialogActionArea";
			w3.Spacing = 10;
			w3.BorderWidth = ((uint)(5));
			w3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child dialogActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonToday = new global::Gtk.Button ();
			this.buttonToday.CanFocus = true;
			this.buttonToday.Name = "buttonToday";
			this.buttonToday.UseUnderline = true;
			this.buttonToday.Label = global::Mono.Unix.Catalog.GetString ("_Hoy");
			this.AddActionWidget (this.buttonToday, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w3 [this.buttonToday]));
			w4.Expand = false;
			w4.Fill = false;
			// Container child dialogActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonDefault = new global::Gtk.Button ();
			this.buttonDefault.CanFocus = true;
			this.buttonDefault.Name = "buttonDefault";
			this.buttonDefault.UseUnderline = true;
			this.buttonDefault.Label = global::Mono.Unix.Catalog.GetString ("_Defecto");
			this.AddActionWidget (this.buttonDefault, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w3 [this.buttonDefault]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 243;
			this.DefaultHeight = 211;
			this.Show ();
		}
	}
}
