
// This file has been generated by the GUI designer. Do not modify.
namespace Hamekoz.UI.Gtk
{
	public partial class WidgetCheckbox
	{
		private global::Gtk.Table table2;
		
		private global::Gtk.CheckButton checkbutton;
		
		private global::Gtk.DrawingArea drawingarea5;
		
		private global::Gtk.DrawingArea drawingarea6;
		
		private global::Gtk.DrawingArea drawingarea7;
		
		private global::Gtk.DrawingArea drawingarea8;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Hamekoz.UI.Gtk.WidgetCheckbox
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Hamekoz.UI.Gtk.WidgetCheckbox";
			// Container child Hamekoz.UI.Gtk.WidgetCheckbox.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.checkbutton = new global::Gtk.CheckButton ();
			this.checkbutton.CanFocus = true;
			this.checkbutton.Name = "checkbutton";
			this.checkbutton.Label = global::Mono.Unix.Catalog.GetString ("Checkbox");
			this.checkbutton.Active = true;
			this.checkbutton.DrawIndicator = true;
			this.checkbutton.UseUnderline = true;
			this.table2.Add (this.checkbutton);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbutton]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.drawingarea5 = new global::Gtk.DrawingArea ();
			this.drawingarea5.Name = "drawingarea5";
			this.table2.Add (this.drawingarea5);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.drawingarea5]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.drawingarea6 = new global::Gtk.DrawingArea ();
			this.drawingarea6.Name = "drawingarea6";
			this.table2.Add (this.drawingarea6);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.drawingarea6]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.drawingarea7 = new global::Gtk.DrawingArea ();
			this.drawingarea7.Name = "drawingarea7";
			this.table2.Add (this.drawingarea7);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.drawingarea7]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(2));
			w4.RightAttach = ((uint)(3));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.drawingarea8 = new global::Gtk.DrawingArea ();
			this.drawingarea8.Name = "drawingarea8";
			this.table2.Add (this.drawingarea8);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.drawingarea8]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
