
// This file has been generated by the GUI designer. Do not modify.
namespace Hamekoz.UI.Gtk
{
	public partial class DialogCalendar
	{
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{

		}
	}
}
