
// This file has been generated by the GUI designer. Do not modify.
namespace Hamekoz.UI.Gtk
{
	public partial class WidgetFromAndToDate
	{
		private global::Gtk.Table table1;
		
		private global::Gtk.DrawingArea drawingarea1;
		
		private global::Gtk.DrawingArea drawingarea2;
		
		private global::Gtk.DrawingArea drawingarea3;
		
		private global::Gtk.DrawingArea drawingarea4;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label labelFrom;
		
		private global::Hamekoz.UI.Gtk.DatePicker datepickerFrom;
		
		private global::Gtk.Label labelTo;
		
		private global::Hamekoz.UI.Gtk.DatePicker datepickerTo;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Hamekoz.UI.Gtk.WidgetFromAndToDate
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Hamekoz.UI.Gtk.WidgetFromAndToDate";
			// Container child Hamekoz.UI.Gtk.WidgetFromAndToDate.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea1 = new global::Gtk.DrawingArea ();
			this.drawingarea1.Name = "drawingarea1";
			this.table1.Add (this.drawingarea1);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.drawingarea1]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea2 = new global::Gtk.DrawingArea ();
			this.drawingarea2.Name = "drawingarea2";
			this.table1.Add (this.drawingarea2);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.drawingarea2]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea3 = new global::Gtk.DrawingArea ();
			this.drawingarea3.Name = "drawingarea3";
			this.table1.Add (this.drawingarea3);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.drawingarea3]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea4 = new global::Gtk.DrawingArea ();
			this.drawingarea4.Name = "drawingarea4";
			this.table1.Add (this.drawingarea4);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.drawingarea4]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 10;
			this.vbox2.BorderWidth = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelFrom = new global::Gtk.Label ();
			this.labelFrom.Name = "labelFrom";
			this.labelFrom.Xalign = 0F;
			this.labelFrom.LabelProp = global::Mono.Unix.Catalog.GetString ("Desde");
			this.vbox2.Add (this.labelFrom);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.labelFrom]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.datepickerFrom = new global::Hamekoz.UI.Gtk.DatePicker ();
			this.datepickerFrom.WidthRequest = 200;
			this.datepickerFrom.HeightRequest = 27;
			this.datepickerFrom.Events = ((global::Gdk.EventMask)(256));
			this.datepickerFrom.Name = "datepickerFrom";
			this.datepickerFrom.ButtonsVisible = false;
			this.datepickerFrom.DefaultDate = new global::System.DateTime (0);
			this.datepickerFrom.Date = new global::System.DateTime (0);
			this.vbox2.Add (this.datepickerFrom);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.datepickerFrom]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelTo = new global::Gtk.Label ();
			this.labelTo.Name = "labelTo";
			this.labelTo.Xalign = 0F;
			this.labelTo.LabelProp = global::Mono.Unix.Catalog.GetString ("Hasta");
			this.vbox2.Add (this.labelTo);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.labelTo]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.datepickerTo = new global::Hamekoz.UI.Gtk.DatePicker ();
			this.datepickerTo.WidthRequest = 200;
			this.datepickerTo.HeightRequest = 27;
			this.datepickerTo.Events = ((global::Gdk.EventMask)(256));
			this.datepickerTo.Name = "datepickerTo";
			this.datepickerTo.ButtonsVisible = false;
			this.datepickerTo.DefaultDate = new global::System.DateTime (0);
			this.datepickerTo.Date = new global::System.DateTime (0);
			this.vbox2.Add (this.datepickerTo);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.datepickerTo]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			this.table1.Add (this.vbox2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.vbox2]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
