
// This file has been generated by the GUI designer. Do not modify.
namespace Hamekoz.UI.Gtk
{
	public partial class MasterWindow
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.VBox vboxPrincipal;
		
		private global::Gtk.HPaned hpaned;
		
		private global::Gtk.VBox vboxMenu;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView treeviewMenuPrincipal;
		
		private global::Gtk.Button buttonUser;
		
		private global::Gtk.VBox vboxWidget;
		
		private global::Gtk.Statusbar statusbar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Hamekoz.UI.Gtk.MasterWindow
			this.Name = "Hamekoz.UI.Gtk.MasterWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Postres Balcarce");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child Hamekoz.UI.Gtk.MasterWindow.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vboxPrincipal = new global::Gtk.VBox ();
			this.vboxPrincipal.Name = "vboxPrincipal";
			this.vboxPrincipal.Spacing = 6;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.hpaned = new global::Gtk.HPaned ();
			this.hpaned.CanFocus = true;
			this.hpaned.Name = "hpaned";
			this.hpaned.Position = 250;
			// Container child hpaned.Gtk.Paned+PanedChild
			this.vboxMenu = new global::Gtk.VBox ();
			this.vboxMenu.Name = "vboxMenu";
			this.vboxMenu.Spacing = 6;
			// Container child vboxMenu.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeviewMenuPrincipal = new global::Gtk.TreeView ();
			this.treeviewMenuPrincipal.CanFocus = true;
			this.treeviewMenuPrincipal.Name = "treeviewMenuPrincipal";
			this.GtkScrolledWindow1.Add (this.treeviewMenuPrincipal);
			this.vboxMenu.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMenu [this.GtkScrolledWindow1]));
			w3.Position = 0;
			// Container child vboxMenu.Gtk.Box+BoxChild
			this.buttonUser = new global::Gtk.Button ();
			this.buttonUser.CanFocus = true;
			this.buttonUser.Name = "buttonUser";
			this.buttonUser.UseUnderline = true;
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-quit", global::Gtk.IconSize.Menu);
			this.buttonUser.Image = w4;
			this.vboxMenu.Add (this.buttonUser);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxMenu [this.buttonUser]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.hpaned.Add (this.vboxMenu);
			global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.hpaned [this.vboxMenu]));
			w6.Resize = false;
			// Container child hpaned.Gtk.Paned+PanedChild
			this.vboxWidget = new global::Gtk.VBox ();
			this.vboxWidget.Name = "vboxWidget";
			this.vboxWidget.Spacing = 6;
			this.hpaned.Add (this.vboxWidget);
			this.vboxPrincipal.Add (this.hpaned);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.hpaned]));
			w8.Position = 0;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.statusbar = new global::Gtk.Statusbar ();
			this.statusbar.Name = "statusbar";
			this.statusbar.Spacing = 6;
			this.vboxPrincipal.Add (this.statusbar);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.statusbar]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			w1.Add (this.vboxPrincipal);
			this.GtkScrolledWindow.Add (w1);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 515;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
