
// This file has been generated by the GUI designer. Do not modify.
namespace Hamekoz.UI.Gtk
{
	public partial class SearchableTreeView
	{
		private global::Gtk.VBox vbox;
		
		private global::Gtk.HBox hbox;
		
		private global::Gtk.Entry entryBuscar;
		
		private global::Gtk.Image imageBuscar;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Hamekoz.UI.Gtk.SearchableTreeView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Hamekoz.UI.Gtk.SearchableTreeView";
			// Container child Hamekoz.UI.Gtk.SearchableTreeView.Gtk.Container+ContainerChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.vbox.Spacing = 6;
			// Container child vbox.Gtk.Box+BoxChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			this.hbox.Spacing = 6;
			this.hbox.BorderWidth = ((uint)(3));
			// Container child hbox.Gtk.Box+BoxChild
			this.entryBuscar = new global::Gtk.Entry ();
			this.entryBuscar.WidthRequest = 20;
			this.entryBuscar.Name = "entryBuscar";
			this.entryBuscar.IsEditable = true;
			this.entryBuscar.ActivatesDefault = true;
			this.entryBuscar.InvisibleChar = '●';
			this.hbox.Add (this.entryBuscar);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox [this.entryBuscar]));
			w1.Position = 0;
			// Container child hbox.Gtk.Box+BoxChild
			this.imageBuscar = new global::Gtk.Image ();
			this.imageBuscar.Name = "imageBuscar";
			this.imageBuscar.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
			this.hbox.Add (this.imageBuscar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox [this.imageBuscar]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox.Add (this.hbox);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview = new global::Gtk.TreeView ();
			this.treeview.CanFocus = true;
			this.treeview.Name = "treeview";
			this.GtkScrolledWindow.Add (this.treeview);
			this.vbox.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox [this.GtkScrolledWindow]));
			w5.Position = 1;
			this.Add (this.vbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
