name: Continuous Delivery

on:
  workflow_call:

jobs:
  github-packages:
    name: Nuget to Github Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: "global.json"
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.2.0
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: version # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v1.2.0
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Pack nuget
        run: |
          dotnet pack \
            --output ./nugets \
            --configuration Release \
            -p:Version=${{ steps.version.outputs.nuGetVersion }}
      - name: Check if generates nugets packages
        id: has-nugets
        uses: andstor/file-existence-action@v3
        with:
          files: "./nugets/*.nupkg"
      - name: Upload artifact
        if: steps.has-nugets.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: nugets
          path: ./nugets/*.nupkg
      - name: Delivery nuget to Github Packages
        if: steps.has-nugets.outputs.files_exists == 'true'
        run: |
          dotnet nuget push ./nugets/*.nupkg \
            --skip-duplicate \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source 'https://nuget.pkg.github.com/${{ github.REPOSITORY_OWNER }}/index.json'
